export const LOG_OUT_START = 'LOG_OUT_START';
export const LOG_OUT_SUCCESS = 'LOG_OUT_START';
export const LOG_OUT_ERROR = 'LOG_OUT_START';

export const GET_OAUTH_TOKEN_NO_CHANGE = 'GET_OAUTH_TOKEN_NO_CHANGE';
export const GET_OAUTH_TOKEN_START = 'GET_OAUTH_TOKEN_START';
export const GET_OAUTH_TOKEN_SUCCESS = 'GET_OAUTH_TOKEN_SUCCESS';
export const GET_OAUTH_TOKEN_ERROR = 'GET_OAUTH_TOKEN_ERROR';
