// TasklistList
export const FETCH_TASKLIST_LIST_START = 'FETCH_TASKLIST_LIST_START';
export const FETCH_TASKLIST_LIST_SUCCESS = 'FETCH_TASKLIST_LIST_SUCCESS';
export const FETCH_TASKLIST_LIST_ERROR = 'FETCH_TASKLIST_LIST_ERROR';

// Task
export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';

// Account
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const LOG_OUT_START = 'LOG_OUT_START';
export const LOG_OUT_SUCCESS = 'LOG_OUT_START';
export const LOG_OUT_ERROR = 'LOG_OUT_START';
export const FETCH_OAUTH_TOKEN_START = 'FETCH_OAUTH_TOKEN_START';
export const FETCH_OAUTH_TOKEN_SUCCESS = 'FETCH_OAUTH_TOKEN_SUCCESS';
export const FETCH_OAUTH_TOKEN_ERROR = 'FETCH_OAUTH_TOKEN_ERROR';
