

export enum NotifyType {
  TODO,
  TASK,
  TASKLIST,
}

export enum Page {
  POPUP,
  BACKGROUND,
  OPTIONS,
}


export enum ErrorCode {
  UNKNOW = 'UNKNOW',
  LOGIN_REDIRECT = 'LOGIN_REDIRECT',
  ACQUIRE_TOKEN_REDIRECT = 'ACQUIRE_TOKEN_REDIRECT',
  LAUNCH_WEB_AUTH_FLOW = 'LAUNCH_WEB_AUTH_FLOW',
  HANDLE_REDIRECT_PROMISE = 'HANDLE_REDIRECT_PROMISE',
  LOGOUT_REDIRECT = 'LOGOUT_REDIRECT',
  ACQUIRE_TOKEN_SILENT = 'ACQUIRE_TOKEN_SILENT',
  ACQUIRE_TOKEN = 'ACQUIRE_TOKEN',
  CREATE_TAB = 'CREATE_TAB',
  QUERY_TAB = 'QUERY_TAB',
  NOT_FOUND_TAB = 'NOT_FOUND_TAB',
  SEND_MESSAGE = 'SEND_MESSAGE',
  CREATE_MENU = 'CREATE_MENU',
  NOTIFY_SHOW = 'NOTIFY_SHOW',
  NOTIFY_CLEAR = 'NOTIFY_CLEAR',
  REQUEST = 'REQUEST',
  RESPONSE = 'RESPONSE',

  REQUEST_TODOLISTS = 'REQUEST_TODOLISTS',
  REQUEST_CREATE_TASK = 'REQUEST_CREATE_TASK'
}

export enum EThemes {
  BASIC = 'basic',
  DEFAULT = 'default',
}

export enum EQuickTaskTitle {
  SELECTION = 'SELECTION',
  ACTIVE_TAB = 'ACTIVE_TAB',
}


export enum ETARGET {
  CHROME = "chrome",
  EDGE = 'edge',
  FIREFOX = "firefox"
}