// Task
export const EDIT_TASK = 'EDIT_TASK';
export const EDIT_SELECTED_TASKLIST = 'EDIT_SELECTED_TASKLIST';
export const EDIT_BOOKMARKED = 'EDIT_BOOKMARKED';

export const RESET_TASK = 'RESET_TASK';

export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';

export const FETCH_TASKLIST_LIST_START = 'FETCH_TASKLIST_LIST_START';
export const FETCH_TASKLIST_LIST_SUCCESS = 'FETCH_TASKLIST_LIST_SUCCESS';
export const FETCH_TASKLIST_LIST_ERROR = 'FETCH_TASKLIST_LIST_ERROR';
