// Task
export const EDIT_TITLE = 'EDIT_TITLE';
export const EDIT_BODY = 'EDIT_BODY';
export const EDIT_TASKLIST = 'EDIT_TASKLIST';
export const EDIT_REMINDER_DATE = 'EDIT_REMINED_DATE';
export const EDIT_BOOKMARKS = 'EDIT_BOOKMARKS';
export const EDIT_IMPORTANCE = 'EDIT_IMPORTANCE';

export const RESET_TASK = 'RESET_TASK';

export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';

export const FETCH_TASKLIST_LIST_START = 'FETCH_TASKLIST_LIST_START';
export const FETCH_TASKLIST_LIST_SUCCESS = 'FETCH_TASKLIST_LIST_SUCCESS';
export const FETCH_TASKLIST_LIST_ERROR = 'FETCH_TASKLIST_LIST_ERROR';
