// FETCH_TASKLIST_LIST
export const FETCH_TASKLIST_LIST_START = 'FETCH_TASKLIST_LIST_START';
export const FETCH_TASKLIST_LIST_SUCCESS = 'FETCH_TASKLIST_LIST_SUCCESS';
export const FETCH_TASKLIST_LIST_ERROR = 'FETCH_TASKLIST_LIST_ERROR';

// EDIT_TASK
export const EDIT_TASK_TITLE = 'EDIT_TASK_TITLE';
export const EDIT_TASK_CONTENT = 'EDIT_TASK_CONTENT';
export const EDIT_TASK_REMINDER_DATETIME = 'EDIT_TASK_REMINDER_DATETIME';
export const EDIT_SELECTED_TASKLIST = 'EDIT_SELECTED_TASKLIST';
export const EDIT_IMPORTANCE = 'EDIT_IMPORTANCE';
export const EDIT_BOOKMARKED = 'EDIT_BOOKMARKED';
export const RESET_TASK = 'RESET_TASK';

// CREATE_TASK
export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';

// MESSAGE
export const OPEN_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE';
export const OPEN_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';
