// TasklistList
export const FETCH_TASKLIST_LIST_START = 'FETCH_TASKLIST_LIST_START';
export const FETCH_TASKLIST_LIST_SUCCESS = 'FETCH_TASKLIST_LIST_SUCCESS';
export const FETCH_TASKLIST_LIST_ERROR = 'FETCH_TASKLIST_LIST_ERROR';
