# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Upload

on:
  push:
    branches:
      - "ci/gh-action"
    tags:        
      - v*
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inital Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          
      - name: Create env file
        run: |
            cat << EOF > .env.production
            CHROME_CLIENT_ID="a5491fb2-111a-4c43-976c-280a507814dc"
            EDGE_CLIENT_ID="ce33022f-91e6-470c-8ccb-fefba8207f1b"
            FIREFOX_CLIENT_ID="15eec8a0-7d1e-4e93-aa7c-31795b3d6bac"
            CHROME_STORE_UPLOADER_EXTENSION_ID="ffpljgmbiankjaokoefefmkoghcgoodn"
            CHROME_STORE_UPLOADER_CLIENT_ID="846943702071-dg8uf689j8bsn816avetglmtpis4hr3m.apps.googleusercontent.com"
            CHROME_STORE_UPLOADER_REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}
            EOF

      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build
        run: npm run build:chrome

      - name: Upload
        run: npm run upload:chrome
