# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Upload

on:
  push:
    tags:        
      - v*
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inital Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      - name: Create env file
        run: |
            cat << EOF > .env.production
            BUILD_TARGET="ChromeStore"
            EXTENSION_ID="ffpljgmbiankjaokoefefmkoghcgoodn"
            MSAL_CLIENT_ID="a5491fb2-111a-4c43-976c-280a507814dc"
            SENTRY_DSN="https://365de3b2d6514a4caca2e06294ff74d0@o1093323.ingest.sentry.io/6112552"
            GTM_ID="GTM-WVNS69V"
            CLIENT_ID="846943702071-dg8uf689j8bsn816avetglmtpis4hr3m.apps.googleusercontent.com"
            REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}
            EOF

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Zip
        run: npm run zip

      - name: Upload
        run: npm run upload
