# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inital Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload
        run: npm run upload
